### ISSUE TITLE
iOS profiles:manage:devices doesn't work

### ISSUE THREAD

**Issue by sfransen** [nomad/cupertino#201]
iOS profiles:manage:devices doesn't work
error: undefined method `name' for nil:NilClass. Use --trace to view backtrace
 The  add device to provision profile doesn't work.
It started this last weekend.

Anyone have a clue in what is happening.
 I really need this features I have 460 provision profiles in my license.
 Please help.

**Comment by vanger-cat** [comment]
Looks like this issue is about the same with issue #195 that is fixed by this pull request #196 
Isn't it?

**Comment by sfransen** [comment]
but the add device to provision profile is not fixed yet.

**Comment by sfransen** [comment]
I tried raising page number to even 5000 and it still not working

**Comment by danieljimenez** [comment]
Seeing the same thing here.

**Comment by danieljimenez** [comment]
Version 1.3.3

**Comment by sfransen** [comment]
Not working in that version

**Comment by sfransen** [comment]
#195 is for list only and Page doesn't help this bug name is not defined
error: undefined method `name' for nil:NilClass. Use --trace to view backtrace

**Comment by tehnoir** [comment]
Same here. #196 fixed the list issues, but profiles:devices:add now fails for me:

`/Library/Ruby/Gems/2.0.0/gems/cupertino-1.0.2/lib/cupertino/provisioning_portal/commands/profiles.rb:139:in `block (5 levels) in <top (required)>': undefined method `name' for nil:NilClass (NoMethodError)`

**Comment by sfransen** [comment]
anyone working on this one?

**Comment by sfransen** [comment]
Ok I have it working You have to make sure your page number is greater then number of devices you have in your Licenses in my case I need the number to be 50001 as I have 5000 in my license
line 118 in agent.rb change to 
        device_data_url += "&pageSize=5001&pageNumber=1&sort=name=asc"

and this is working again for me.

**Comment by tehnoir** [comment]
Thanks @sfransen. That seems to have resolved the issue for me.

**Comment by mattt** [comment]
Fixed by #196 and #216.
